//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppe_foods.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelanggan
    {
        public int ID_Pelanggan { get; set; }
        public string Nama { get; set; }
        public string Telepon { get; set; }
    }
}
