//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ppe_foods.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Penjualan
    {
        public int ID_Penjualan { get; set; }
        public Nullable<int> ID_Barang { get; set; }
        public System.DateTime Tanggal { get; set; }
        public int Jumlah { get; set; }
    
        public virtual Barang Barang { get; set; }
        private DBFoodsEntities dbo = new DBFoodsEntities();
        public Barang ModelBarang
        {
            get
            {
                return dbo.Barangs.Where(e => e.ID_Barang == ID_Barang).SingleOrDefault();
            }
            set
            {
                ID_Barang = value.ID_Barang;
            }
        }
    }
}
